# Generated by Django 5.0.7 on 2024-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="publicites/")),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
